### ISSUE TITLE
make clean fails on windows

### ISSUE THREAD

**Issue by dragonchaser** [rancher-sandbox/hypper#41]
running `make clean` on windows fails with the following error:

```
PS C:\Users\user\hypper> make clean
The system cannot find the path specified.
File not found - *.go
rm C:/Users/user/hypper/bin/"hypper.exe"
process_begin: CreateProcess(NULL, rm C:/Users/user/hypper/bin/hypper.exe, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:82: clean] Error 2
```

**Comment by Itxaka** [comment]
This is very interesting, Im assuming you tried to build and clean under cygwin @dragonchaser ?

This seems to be related to using a combination of go for windows + a POSIX env, as go for windows knows that its running on windows its uses its full path to output the binaries. So using `-o /home/itxaka/hypper/bin/hypper.exe` is really building it to whatever drive go is installed + the output path (in my case `C:\home\itxaka\hypper\bin` as I have go installed under `C:\go`)

**But** the cleaning does nothing like that, because it knows nothing about windows. rm gets a path and tries to clean it but doesnt find anything because its referring to the "fake" environment that cygwin sets instead of the full windows path where the binary installs it.


An easy fix is to use relative paths instead of full paths, let me send a quick patch

**Comment by dragonchaser** [comment]
No native build.
