### ISSUE TITLE
Investigate and move away from deprecated io/ioutil on go 1.16

### ISSUE THREAD

**Issue by viccuad** [rancher-sandbox/hypper#48]
`io/ioutil` is deprecated in go 1.16: https://golang.org/doc/go1.16#ioutil

Move away from it. Our uses:

```console
vic@viccuad ~/suse/hypper $ ag ioutil
cmd/hypper/require/args_test.go
20:     "io/ioutil"
74:                     cmd.SetOutput(ioutil.Discard)

cmd/hypper/hypper_test.go
5:      "io/ioutil"
97:             KubeClient:   &kubefake.PrintingKubeClient{Out: ioutil.Discard},

cmd/hypper/hypper.go
4:      "io/ioutil"
74:     actionConfig.KubeClient = &kubefake.PrintingKubeClient{Out: ioutil.Discard}
77:             b, err := ioutil.ReadFile(path)

internal/test/test.go
22:     "io/ioutil"
65:     actual, err := ioutil.ReadFile(actualFileName)
85:     expected, err := ioutil.ReadFile(filename)
101:    return ioutil.WriteFile(filename, normalize(in), 0666)

```

**Comment by mattfarina** [comment]
While it's nice to be on the bleeding edge, one of the goals of this project is to be imported by others and used as a go package.

I just looked at rancher/rancher and it's using Go 1.14. I wouldn't be surprised if they move to 1.15 next rather than right to 1.16. We should be conservative with adopting the 1.16 changes for wider support. When ranchers other stuff moves to 1.16 we could look at a move.

**Comment by viccuad** [comment]
Thanks for the information :). Fair enough, I was too eager with book keeping. Closing this for now then, it's going to be quite a while.
